version: "3.9"
services:
  init:
    extends:
      file: common.yml
      service: app
    command: "/opt/acme-posh/init.ps1"
  renew:
    extends:
      file: common.yml
      service: app
    command: "/opt/acme-posh/renew.ps1"
volumes:
  acme-posh:
